import path from "node:path";
import { readFileSync, writeFileSync } from "node:fs";
import { en } from "../src/i18n/en";
import { zh, type MessageKey } from "../src/i18n/zh-CN";

const keys = ["startup.failed", "startup.loading", "startup.scriptFailed", "startup.cspBlocked",
  "startup.resource", "startup.loadingProjects", "startup.file", "common.edit", "startup.view",
  "startup.help", "sidebar.newChat", "app.apps", "sidebar.projects", "common.settings"] satisfies MessageKey[];
const copy = (messages: Record<MessageKey, string>) => Object.fromEntries(keys.map((key) => [key, messages[key]]));

export async function generateBootLocale(): Promise<string> {
  const core = path.resolve(import.meta.dir, "../src/locale-core.ts").replaceAll("\\", "/");
  const result = await Bun.build({
    entrypoints: ["qone:boot-locale"], target: "browser", format: "iife", minify: true,
    plugins: [{ name: "boot-locale", setup(build) {
      build.onResolve({ filter: /^qone:boot-locale$/ }, () => ({ path: "boot", namespace: "qone" }));
      build.onLoad({ filter: /^boot$/, namespace: "qone" }, () => ({ loader: "ts", contents: `
        import { GENERAL_SETTINGS_KEY, normalizeLanguageSetting, resolveLocale } from ${JSON.stringify(core)};
        const messages = ${JSON.stringify({ en: copy(en), "zh-CN": copy(zh) })};
        let saved = {};
        try { saved = JSON.parse(localStorage.getItem(GENERAL_SETTINGS_KEY) ?? "{}") ?? {}; } catch {}
        const locale = resolveLocale(normalizeLanguageSetting(saved.language));
        document.documentElement.lang = locale;
        window.qoneBootText = key => messages[locale][key];
        for (const node of document.querySelectorAll("[data-qone-boot-text]"))
          node.textContent = window.qoneBootText(node.dataset.qoneBootText);
        for (const node of document.querySelectorAll("[data-qone-boot-label]"))
          node.setAttribute("aria-label", window.qoneBootText(node.dataset.qoneBootLabel));
      ` }));
    } }],
  });
  if (!result.success) throw new AggregateError(result.logs, "Boot locale generation failed");
  return "// Generated by scripts/generate-boot-locale.ts.\n" + await result.outputs[0]!.text();
}

if (import.meta.main) {
  const file = path.resolve(import.meta.dir, "../public/boot-locale.js");
  const output = await generateBootLocale();
  if (process.argv.includes("--check")) {
    if (readFileSync(file, "utf8") !== output) throw new Error("Boot translations are stale; run bun scripts/generate-boot-locale.ts");
  } else writeFileSync(file, output);
}
